"""Format scraped posts into an HTML email digest."""

from datetime import datetime, timezone


def build_digest(posts: list[dict], max_posts: int = 10) -> str:
    """Deduplicate, sort, and pick top posts, then return an HTML email body."""
    if not posts:
        return _wrap_html("<p>No posts found today. The scraping may need attention.</p>")

    # Deduplicate by URL
    seen_urls = set()
    unique = []
    for p in posts:
        url = p.get("url", "")
        if url and url not in seen_urls:
            seen_urls.add(url)
            unique.append(p)

    # Sort: trending first, then by likes descending
    unique.sort(key=lambda p: (not p.get("is_trending"), -p.get("likes", 0)))

    top = unique[:max_posts]
    today = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d")

    html = f"""
    <h1 style="font-family:-apple-system,BlinkMacSystemFont,sans-serif;color:#1d9bf0;">
        X Daily Digest &mdash; {today}
    </h1>
    <p style="font-family:-apple-system,BlinkMacSystemFont,sans-serif;color:#536471;">
        {len(top)} trending &amp; popular posts from X
    </p>
    <hr style="border:1px solid #eff3f4;">
    """

    for i, post in enumerate(top, 1):
        tag = "🔥 Trending" if post.get("is_trending") else "⭐ Popular"
        html += f"""
        <div style="font-family:-apple-system,BlinkMacSystemFont,sans-serif;
                    margin-bottom:20px;padding:16px;border:1px solid #eff3f4;
                    border-radius:12px;max-width:600px;">
            <div style="margin-bottom:8px;">
                <span style="background:#1d9bf0;color:#fff;padding:2px 8px;
                             border-radius:4px;font-size:12px;">{tag}</span>
                <strong style="margin-left:8px;">{_esc(post.get('author', 'Unknown'))}</strong>
                <span style="color:#536471;">@{_esc(post.get('handle', ''))}</span>
            </div>
            <p style="font-size:15px;line-height:1.5;color:#0f1419;
                      white-space:pre-wrap;margin:8px 0;">
                {_esc(post.get('text', ''))}
            </p>
            <div style="color:#536471;font-size:13px;margin-bottom:6px;">
                ❤ {_fmt_num(post.get('likes', 0))} &nbsp;
                🔁 {_fmt_num(post.get('retweets', 0))} &nbsp;
                💬 {_fmt_num(post.get('replies', 0))}
            </div>
            <a href="{_esc(post.get('url', '#'))}"
               style="color:#1d9bf0;text-decoration:none;font-size:13px;">
                View on X &rarr;
            </a>
        </div>
        """

    html += """
    <hr style="border:1px solid #eff3f4;">
    <p style="font-family:-apple-system,BlinkMacSystemFont,sans-serif;color:#536471;font-size:12px;">
        Generated by x-daily-digest bot
    </p>
    """

    return _wrap_html(html)


def _wrap_html(body: str) -> str:
    return f"""<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"></head>
<body style="background:#fff;padding:20px;">
{body}
</body>
</html>"""


def _esc(text: str) -> str:
    """Minimal HTML escaping."""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def _fmt_num(n: int) -> str:
    """Pretty-print engagement: 1234 → '1.2K'"""
    if n >= 1_000_000:
        return f"{n / 1_000_000:.1f}M"
    if n >= 1_000:
        return f"{n / 1_000:.1f}K"
    return str(n)
